# MD013/line-length - Line Length
MD013:
  # Number of characters
  line_length: 120
  # Number of characters for headings
  heading_line_length: 80
  # Number of characters for code blocks
  code_block_line_length: 100
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: false
  # Include headings
  headings: true
  # Include headers
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# MD041/first-line-heading/first-line-h1 First line in a file should be a top-level
# This complains about badges
MD041: false